#!/usr/bin/env python3
"""
ClawFlow Research Pipeline - Working Version
简化但完整可用的自动化研究管道
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from clawflow import WorkflowEngine
from datetime import datetime
import json


def run_research(topic: str, depth: str = "standard"):
    """执行研究"""
    
    print(f"\n{'='*60}")
    print(f"🔬 ClawFlow Research Pipeline")
    print(f"{'='*60}")
    print(f"Topic: {topic}")
    print(f"Depth: {depth}")
    
    # 参数
    search_count = 10 if depth == "deep" else 5
    fetch_limit = 5 if depth == "deep" else 3
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_base = f"/tmp/clawflow_research/research_{topic.replace(' ', '_')[:20]}_{timestamp}"
    
    # 构建工作流
    workflow = {
        "name": f"Research: {topic}",
        "nodes": [
            # 1. Setup
            {
                "id": "setup",
                "type": "function", 
                "params": {
                    "code": f"output = {{'topic': '{topic}', 'depth': '{depth}', 'count': {search_count}}}"
                }
            },
            
            # 2. Parallel searches
            {
                "id": "search1",
                "type": "skill",
                "params": {
                    "skill": "kimi_search",
                    "params": {"query": topic}
                }
            },
            {
                "id": "search2", 
                "type": "skill",
                "params": {
                    "skill": "kimi_search",
                    "params": {"query": topic}
                }
            },
            
            # 3. Aggregate
            {
                "id": "aggregate",
                "type": "function",
                "params": {
                    "code": """
if isinstance(input, dict) and "__merged__" in input:
    items = input["__merged__"]
elif isinstance(input, list):
    items = input
else:
    items = [input] if input else []

results = []
for item in items:
    if isinstance(item, dict) and 'results' in item:
        results.extend(item['results'])

output = {"results": results, "total": len(results)}
"""
                }
            },
            
            # 4. AI Analysis
            {
                "id": "analyze",
                "type": "llm",
                "params": {
                    "model": "mock",
                    "prompt": "Analyze these search results and provide key insights"
                }
            },
            
            # 5. Build report
            {
                "id": "build_report",
                "type": "function",
                "params": {
                    "code": f"""
report = {{
    "title": "Research: {topic}",
    "topic": "{topic}",
    "generated_at": "{datetime.now().isoformat()}",
    "analysis": input.get('response', 'No analysis'),
    "depth": "{depth}"
}}
output = report
"""
                }
            },
            
            # 6. Save JSON
            {
                "id": "save_json",
                "type": "json",
                "params": {
                    "operation": "write",
                    "path": report_base + ".json"
                }
            },
            
            # 7. Generate Markdown
            {
                "id": "gen_md",
                "type": "function",
                "params": {
                    "code": f"""
report = input
md = f'''# {{report.get('title', 'Research Report')}}

**Topic**: {topic}  
**Generated**: {{report.get('generated_at', 'N/A')}}  
**Depth**: {{report.get('depth', 'standard')}}

## Analysis
{{report.get('analysis', 'No analysis available')}}

---
*Generated by ClawFlow*
'''
path = "{report_base}.md"
with open(path, 'w') as f:
    f.write(md)
output = {{"json": "{report_base}.json", "markdown": path}}
"""
                }
            },
            
            # 8. Output
            {
                "id": "output",
                "type": "output",
                "params": {"type": "print"}
            }
        ],
        "connections": [
            {"from": "setup", "to": "search1"},
            {"from": "setup", "to": "search2"},
            {"from": "search1", "to": "aggregate"},
            {"from": "search2", "to": "aggregate"},
            {"from": "aggregate", "to": "analyze"},
            {"from": "analyze", "to": "build_report"},
            {"from": "build_report", "to": "save_json"},
            {"from": "build_report", "to": "gen_md"},
            {"from": "gen_md", "to": "output"}
        ]
    }
    
    # 执行
    engine = WorkflowEngine()
    
    # 可视化
    print(f"\n[Workflow Structure]")
    print(engine.visualize(workflow, format="ascii"))
    
    result = engine.execute(workflow, verbose=False)
    
    if result.success:
        print(f"\n{'='*60}")
        print("✅ Research Complete!")
        print(f"{'='*60}")
        print(f"\n📄 Generated Files:")
        if isinstance(result.data, dict):
            for k, v in result.data.items():
                print(f"  {k}: {v}")
        
        # 显示报告内容
        try:
            with open(report_base + ".md", 'r') as f:
                content = f.read()
                print(f"\n📝 Report Preview:")
                print("-" * 40)
                print(content[:500] + "..." if len(content) > 500 else content)
                print("-" * 40)
        except:
            pass
        
        return True
    else:
        print(f"\n❌ Failed: {result.error}")
        return False


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("topic", nargs="?", default="Python asyncio")
    parser.add_argument("--depth", "-d", default="quick")
    args = parser.parse_args()
    
    run_research(args.topic, args.depth)
