#!/usr/bin/env python3
"""
ClawFlow Research Pipeline - With Real kimi_search Results
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from clawflow import WorkflowEngine
from datetime import datetime
import json
import subprocess


def get_real_search_results(topic: str) -> list:
    """获取真实搜索结果"""
    print(f"🔍 Searching for: {topic}")
    
    # 使用 kimi_search 工具
    try:
        # 由于 kimi_search 是外部工具，我们创建一个简单的脚本来调用它
        script = f"""
import sys
sys.path.insert(0, '/root/.openclaw/workspace/skills')
from clawflow.nodes import SkillNode
import json

node = SkillNode()
result = node.execute(None, {{'skill': 'kimi_search', 'params': {{'query': '{topic}'}}}}, None)
print(json.dumps(result))
"""
        result = subprocess.run(
            ['python3', '-c', script],
            capture_output=True,
            text=True,
            timeout=30
        )
        
        if result.returncode == 0:
            # 解析最后一行 JSON
            lines = result.stdout.strip().split('\\n')
            for line in reversed(lines):
                try:
                    data = json.loads(line)
                    if 'results' in data:
                        return data.get('results', [])
                except:
                    continue
    except Exception as e:
        print(f"Search error: {e}")
    
    return []


def run_research(topic: str):
    """执行研究"""
    print(f"\n{'='*60}")
    print(f"🔬 ClawFlow Research Pipeline")
    print(f"{'='*60}")
    
    # Step 1: 获取真实搜索结果
    sources = get_real_search_results(topic)
    print(f"✓ Found {len(sources)} sources")
    
    if not sources:
        print("❌ No results found")
        return False
    
    # Step 2: 构建工作流处理结果
    print(f"\n[2/3] Processing with ClawFlow...")
    
    workflow = {
        "name": f"Research: {topic}",
        "nodes": [
            {
                "id": "input",
                "type": "function",
                "params": {
                    "code": f"""
output = {{
    "topic": "{topic}",
    "sources": {json.dumps(sources[:5])},
    "total": {len(sources)}
}}
"""
                }
            },
            {
                "id": "summarize",
                "type": "function",
                "params": {
                    "code": """
# Summarize sources
data = input
sources = data.get('sources', [])
summary = []

for s in sources[:3]:
    if isinstance(s, dict):
        summary.append({
            "title": s.get('title', 'N/A')[:80],
            "url": s.get('url', ''),
            "snippet": s.get('snippet', '')[:200]
        })

output = {
    "topic": data.get('topic'),
    "summary": summary,
    "total": data.get('total')
}
"""
                }
            },
            {
                "id": "ai_insights",
                "type": "llm",
                "params": {
                    "model": "mock",
                    "prompt": """Analyze these search results and provide key insights.

Topic: $input.topic
Results: $input.summary

Format:
## Key Findings
- Finding 1
- Finding 2

## Recommendations
1. Recommendation 1
2. Recommendation 2"""
                }
            },
            {
                "id": "generate_report",
                "type": "function",
                "params": {
                    "code": f"""
from datetime import datetime
import json

topic = "{topic}"
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
base_path = f"/tmp/clawflow_research/research_{{topic.replace(' ', '_')[:20]}}_{{timestamp}}"

# Build report
report = {{
    "metadata": {{
        "title": f"Research Report: {topic}",
        "generated_at": datetime.now().isoformat(),
        "engine": "ClawFlow + kimi_search",
        "sources_count": input.get('total', 0)
    }},
    "topic": topic,
    "sources": input.get('summary', []),
    "ai_analysis": input.get('response', 'No analysis')
}}

# Save JSON
json_path = base_path + ".json"
with open(json_path, 'w') as f:
    json.dump(report, f, indent=2)

# Save Markdown
md_path = base_path + ".md"
md_content = f'''# {{report['metadata']['title']}}

**Generated**: {{report['metadata']['generated_at']}}  
**Sources**: {{report['metadata']['sources_count']}}  
**Engine**: {{report['metadata']['engine']}}

## Topic
{topic}

## AI Analysis
{{report['ai_analysis']}}

## Sources
'''

for i, s in enumerate(report['sources'], 1):
    md_content += f"{{i}}. **{{s.get('title', 'N/A')}}**\\n"
    md_content += f"   - {{s.get('url', '')}}\\n"
    md_content += f"   - {{s.get('snippet', '')}}\\n\\n"

md_content += '''
---
*Generated by ClawFlow Research Pipeline with Real Search*
'''

with open(md_path, 'w') as f:
    f.write(md_content)

output = {{
    "json_path": json_path,
    "markdown_path": md_path,
    "sources_count": report['metadata']['sources_count']
}}
"""
                }
            },
            {
                "id": "complete",
                "type": "output",
                "params": {}
            }
        ],
        "connections": [
            {"from": "input", "to": "summarize"},
            {"from": "summarize", "to": "ai_insights"},
            {"from": "ai_insights", "to": "generate_report"},
            {"from": "generate_report", "to": "complete"}
        ]
    }
    
    engine = WorkflowEngine()
    result = engine.execute(workflow, verbose=False)
    
    if result.success:
        print(f"\n{'='*60}")
        print("✅ Research Complete!")
        print(f"{'='*60}")
        
        data = result.data
        print(f"\n📄 Files Generated:")
        print(f"  JSON: {data.get('json_path')}")
        print(f"  Markdown: {data.get('markdown_path')}")
        print(f"  Sources: {data.get('sources_count')}")
        
        # Show preview
        if 'markdown_path' in data:
            try:
                with open(data['markdown_path'], 'r') as f:
                    content = f.read()
                    print(f"\n📝 Preview:")
                    print("-" * 50)
                    print(content[:1000])
                    print("..." if len(content) > 1000 else "")
                    print("-" * 50)
            except Exception as e:
                print(f"Error: {e}")
        
        return True
    else:
        print(f"\n❌ Failed: {result.error}")
        return False


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("topic", nargs="?", default="Python asyncio best practices")
    args = parser.parse_args()
    
    run_research(args.topic)
