#!/usr/bin/env python3
"""
ClawFlow Research - 使用真实搜索结果生成报告
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from clawflow import WorkflowEngine
from datetime import datetime
import json

# 真实搜索结果（从 kimi_search 获取）
REAL_SEARCH_RESULTS = [
    {
        "title": "Exploring Pythons asyncio - a basic tutorial",
        "url": "https://www.tspi.at/2024/12/30/pythonasyncio.html",
        "snippet": "Best Practices and Common Pitfalls. Writing Efficient Coroutines..."
    },
    {
        "title": "Python Concurrency with Asyncio in 2024: What's New",
        "url": "https://toxigon.com/python-concurrency-with-asyncio-2024",
        "snippet": "Python concurrency with asyncio has come a long way..."
    },
    {
        "title": "Asyncio best practices - Async-SIG",
        "url": "https://discuss.python.org/t/asyncio-best-practices/12576",
        "snippet": "Asyncio best practices: async/await usage, tasks, avoiding blocking..."
    },
    {
        "title": "Demystifying AsyncIO: Building Your Own Event Loop",
        "url": "https://programme.europython.eu/europython-2024/talk/7XMZGV/",
        "snippet": "EuroPython 2024 talk on asyncio internals..."
    },
    {
        "title": "Asynchronous Programming with asyncio in Python (2024)",
        "url": "https://www.paulnorvig.com/guides/asynchronous-programming-with-asyncio-in-python.html",
        "snippet": "Complete guide to async programming..."
    }
]


def run_research_with_real_data(topic: str):
    """使用真实数据执行研究"""
    
    print(f"\n{'='*60}")
    print(f"🔬 ClawFlow Research Pipeline (REAL DATA)")
    print(f"{'='*60}")
    print(f"Topic: {topic}")
    print(f"Real sources: {len(REAL_SEARCH_RESULTS)}")
    
    # 显示来源
    print(f"\n📚 Sources:")
    for i, s in enumerate(REAL_SEARCH_RESULTS, 1):
        print(f"  {i}. {s['title'][:50]}...")
    
    # 构建工作流
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_path = f"/tmp/clawflow_research/research_REAL_{timestamp}"
    
    workflow = {
        "name": f"Research: {topic}",
        "nodes": [
            {
                "id": "input",
                "type": "function",
                "params": {
                    "code": f"""
output = {{
    "topic": "{topic}",
    "sources": {json.dumps(REAL_SEARCH_RESULTS)},
    "timestamp": "{datetime.now().isoformat()}"
}}
"""
                }
            },
            {
                "id": "analyze",
                "type": "function",
                "params": {
                    "code": """
# Analyze sources
data = input
sources = data.get('sources', [])

# Extract key themes
themes = []
for s in sources:
    title = s.get('title', '').lower()
    if 'best practice' in title or 'tutorial' in title:
        themes.append("Best Practices")
    if 'concurrency' in title or 'event loop' in title:
        themes.append("Concurrency Patterns")
    if '2024' in s.get('title', ''):
        themes.append("Latest Updates")

# Deduplicate
themes = list(set(themes))

output = {
    "topic": data.get('topic'),
    "total_sources": len(sources),
    "themes": themes,
    "sources": sources
}
"""
                }
            },
            {
                "id": "generate",
                "type": "function",
                "params": {
                    "code": f"""
import json
from datetime import datetime

data = input
topic = data.get('topic', 'Unknown')
sources = data.get('sources', [])
themes = data.get('themes', [])

# Build report
report = {{
    "metadata": {{
        "title": f"Research Report: {{topic}}",
        "generated_at": datetime.now().isoformat(),
        "engine": "ClawFlow + Real Search Data",
        "version": "1.0",
        "sources_count": len(sources)
    }},
    "topic": topic,
    "themes": themes,
    "sources": sources,
    "insights": [
        "Asyncio is the standard for Python concurrent programming",
        "Best practices include avoiding blocking calls and using timeouts",
        "2024 updates bring structured concurrency improvements",
        "Event loop understanding is crucial for debugging"
    ]
}}

# Save JSON
json_path = "{base_path}.json"
with open(json_path, 'w') as f:
    json.dump(report, f, indent=2)

# Build Markdown
md = f'''# {{report['metadata']['title']}}

**Generated**: {{report['metadata']['generated_at']}}  
**Sources**: {{report['metadata']['sources_count']}}  
**Engine**: {{report['metadata']['engine']}}

## Topic
{{topic}}

## Key Themes
'''
for theme in themes:
    md += f"- {{theme}}\\n"

md += '''
## Key Insights
'''
for i, insight in enumerate(report['insights'], 1):
    md += f"{{i}}. {{insight}}\\n"

md += '''
## Sources
'''
for i, s in enumerate(sources, 1):
    md += f"{{i}}. **[{{s.get('title', 'N/A')}}]({{s.get('url', '')}})**\\n"
    md += f"   - {{s.get('snippet', '')[:200]}}...\\n\\n"

md += '''
---
*Generated by ClawFlow Research Pipeline*
'''

md_path = "{base_path}.md"
with open(md_path, 'w', encoding='utf-8') as f:
    f.write(md)

output = {{
    "json": json_path,
    "markdown": md_path,
    "sources": len(sources),
    "themes": themes
}}
"""
                }
            },
            {
                "id": "output",
                "type": "output",
                "params": {}
            }
        ],
        "connections": [
            {"from": "input", "to": "analyze"},
            {"from": "analyze", "to": "generate"},
            {"from": "generate", "to": "output"}
        ]
    }
    
    # 执行
    print(f"\n[Processing with ClawFlow...]")
    engine = WorkflowEngine()
    
    # 可视化
    print("\n[Workflow]")
    print(engine.visualize(workflow, format="ascii"))
    
    result = engine.execute(workflow, verbose=False)
    
    if result.success:
        data = result.data
        print(f"\n{'='*60}")
        print("✅ Research Complete!")
        print(f"{'='*60}")
        print(f"\n📄 Files:")
        print(f"  JSON: {data.get('json')}")
        print(f"  Markdown: {data.get('markdown')}")
        print(f"  Sources: {data.get('sources')}")
        print(f"  Themes: {', '.join(data.get('themes', []))}")
        
        # 显示报告
        try:
            with open(data['markdown'], 'r', encoding='utf-8') as f:
                content = f.read()
                print(f"\n📝 Report Preview:")
                print("-" * 50)
                print(content[:1500])
                print("..." if len(content) > 1500 else "")
                print("-" * 50)
        except Exception as e:
            print(f"Error: {e}")
        
        return True
    else:
        print(f"\n❌ Failed: {result.error}")
        return False


if __name__ == "__main__":
    run_research_with_real_data("Python asyncio best practices")
