#!/usr/bin/env python3
"""
ClawFlow Research Pipeline - Real Search Version
使用真实的 kimi_search 获取数据
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from clawflow import WorkflowEngine
from datetime import datetime
import json


def run_research(topic: str):
    """使用真实搜索执行研究"""
    
    print(f"\n{'='*60}")
    print(f"🔬 ClawFlow Research Pipeline (Real Search)")
    print(f"{'='*60}")
    print(f"Topic: {topic}")
    
    # 执行真实搜索
    print(f"\n[1/3] 执行真实搜索...")
    
    # 由于 kimi_search 是外部工具，我们在 function 节点中调用
    workflow = {
        "name": f"Research: {topic}",
        "nodes": [
            # 1. 搜索并处理结果
            {
                "id": "search",
                "type": "function",
                "params": {
                    "code": f"""
# 调用真实的 kimi_search
import subprocess
import json

topic = "{topic}"
result = subprocess.run(
    ["python3", "-c", f"""
import sys
sys.path.insert(0, '/root/.openclaw/workspace/skills')
from clawflow import WorkflowEngine
from clawflow.nodes import SkillNode
node = SkillNode()
result = node.execute(None, {{'skill': 'kimi_search', 'params': {{'query': '{topic}'}}}}, None)
print(json.dumps(result))
"""],
    capture_output=True,
    text=True
)

if result.returncode == 0:
    import json
    try:
        search_data = json.loads(result.stdout.strip().split('\\n')[-1])
        sources = search_data.get('results', [])[:5]
    except:
        sources = []
else:
    sources = []

output = {{
    "topic": topic,
    "sources": sources,
    "total": len(sources)
}}
"""
                }
            },
            
            # 2. AI 分析
            {
                "id": "analyze",
                "type": "llm",
                "params": {
                    "model": "mock",
                    "prompt": """Based on these search results, provide key insights:

Topic: $input.topic
Sources: $input.sources

Provide:
1. Executive Summary (2-3 sentences)
2. Key Insights (3-5 bullet points)
3. Recommended Actions"""
                }
            },
            
            # 3. 生成报告
            {
                "id": "report",
                "type": "function",
                "params": {
                    "code": f"""
from datetime import datetime

report = {{
    "title": "Research: {topic}",
    "topic": "{topic}",
    "generated_at": datetime.now().isoformat(),
    "analysis": input.get('response', 'No analysis'),
    "sources_count": input.get('total', 0)
}}

# Save JSON
json_path = "/tmp/clawflow_research/research_real_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
with open(json_path, 'w') as f:
    json.dump(report, f, indent=2)

# Save Markdown
md_path = json_path.replace('.json', '.md')
md_content = f'''# {{report['title']}}

**Generated**: {{report['generated_at']}}  
**Sources**: {{report['sources_count']}}

## Analysis
{{report['analysis']}}

---
*Generated by ClawFlow with Real Search*
'''
with open(md_path, 'w') as f:
    f.write(md_content)

output = {{"json": json_path, "markdown": md_path}}
"""
                }
            },
            
            # 4. 输出
            {
                "id": "output",
                "type": "output",
                "params": {"type": "print"}
            }
        ],
        "connections": [
            {"from": "search", "to": "analyze"},
            {"from": "analyze", "to": "report"},
            {"from": "report", "to": "output"}
        ]
    }
    
    # 执行工作流
    engine = WorkflowEngine()
    result = engine.execute(workflow, verbose=False)
    
    if result.success:
        print(f"\n{'='*60}")
        print("✅ Research Complete!")
        print(f"{'='*60}")
        
        data = result.data
        if isinstance(data, dict):
            print(f"\n📄 Generated Files:")
            for k, v in data.items():
                print(f"  {k}: {v}")
                
            # 显示内容
            if 'markdown' in data:
                try:
                    with open(data['markdown'], 'r') as f:
                        content = f.read()
                        print(f"\n📝 Report Preview:")
                        print("-" * 50)
                        print(content[:800] + "..." if len(content) > 800 else content)
                        print("-" * 50)
                except Exception as e:
                    print(f"Error reading: {e}")
        
        return True
    else:
        print(f"\n❌ Failed: {result.error}")
        return False


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("topic", nargs="?", default="Python asyncio best practices")
    args = parser.parse_args()
    
    run_research(args.topic)
